### ISSUE TITLE
abstract out the "query" pattern

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/beacon-api-client#23]
refer this: https://github.com/ralexstokes/beacon-api-client/blob/main/src/api_client.rs#L276-L288

it would be nice to abstract out this pattern and the only tricky bit here is passing in a dynamic number of the query params

we may be able do something like this:

```rust
fn get_with_query<T: serde::Serialize + ?Sized, U: serde::Serialize + serde::de::DeserializeOwned>(&self, path: &str, params: &T) -> Result<U, Error>;

let response: Value<T> = self.get_with_query(path, &[("a", a), ("b", b)])?;
```

where the implementation follows what is given in the linked example, just w/ the generic params

the caller still needs to do the param wrangling and likely into a `Vec` but it does clear up all of the common HTTP code

**Comment by jmcook1186** [comment]
would it make sense to pass optional queries to the existing `http_get()` function and just pass `None` when there are none? Instead of having two `get` functions?

So, something along the following lines (just pseudocode):

```rust
#[derive(Serialize, Deserialize)]
pub struct Query {
    pub key: String,
    pub value: String
}

pub async fn http_get(&self, path: &str, queries: Option<Vec<Query>>) -> Result<reqwest::Response, Error> {
        let request = self.endpoint.join(path)?;
        
        if let Some(queries) = queries{
            for query in queries{
                request = request.query(&[(query.key, query.value)]);
            }
        }
        let response = request.send().await?;
        Ok(response)
    }
```

**Comment by ralexstokes** [comment]
I think we can skip the `Option` layer and just pass a slice of the right type, something like:

```rust
http_get(&self, path: &str, queries: &[(K,V)])
```

where `K` and `V` are `serde::Serialize`

the thing here is that then any caller of `http_get` must pass in a `&[]` if they have no queries which means the average case (as far as I see now) got more expensive just to afford this one special case

the trade off is that we have more code to maintain with a separate function but my intuition says this is the way to go bc it is not that much code to duplicate.

if you really wanted to sort this out, you could write some microbenchmarks and we may even find this is not even worth worrying about :)

**Comment by ralexstokes** [comment]
ended up just going w/ specialization at each site of use; rather than some generic function
