### ISSUE TITLE
Trouble running the examples 

### ISSUE THREAD

**Issue by Perelyn-sama** [ralexstokes/beacon-api-client#49]
I used the public node URL http://public-mainnet-node.ethereum.org/ but when I ran examples/post.rs I got the following error
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Http(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("public-mainnet-node.ethereum.org")), port: None, path: "/eth/v1/builder/validators", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })) })', examples/post.rs:12:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

I'm not sure why It's not working but I'm thinking It has to do with the fact that the default function for `SignedValidatorRegistration` has not been implemented yet. If this is the case I could implement I just need to know the right fields to use.

**Comment by ralexstokes** [comment]
>  http://public-mainnet-node.ethereum.org/

I don't think this is a valid address? it doesn't seem to point anywhere...

**Comment by Perelyn-sama** [comment]
Interesting, I have no idea where I saw that. More importantly, how can I get the examples to work?

**Comment by ralexstokes** [comment]
as written, you'll need a beacon node available on `http://localhost:8080`

you can change the address locally or write a different example if you'd like
