### ISSUE TITLE
Add implementation logic

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/beacon-api-client#8]
A skeleton of the API of the `Client` exists but has essentially no actual implementations.

Let's fix that.

The work can be split fairly fined-grained across endpoints with a higher-level batching across the API "categories":

- [x] beacon: https://ethereum.github.io/beacon-APIs/#/Beacon in #31
- [x] config: https://ethereum.github.io/beacon-APIs/#/Config in #41
- [x] debug: https://ethereum.github.io/beacon-APIs/#/Debug in #44
- [ ] events: https://ethereum.github.io/beacon-APIs/#/Events from @Perelyn-sama 
- [x] node: https://ethereum.github.io/beacon-APIs/#/Node, @jmcook1186 is finishing these
- [x] validator: https://ethereum.github.io/beacon-APIs/#/Validator

To coordinate, post here if you are taking a lock on one of the categories.

**Comment by ralexstokes** [comment]
~I'm assigning @jmcook1186 to the `node` endpoints~

**Comment by jmcook1186** [comment]
Please assign me to finish off the Node namespace too

**Comment by jmcook1186** [comment]
please assign me to Debug namespace.

**Comment by jmcook1186** [comment]
I can take the `validator` namespace next, if it's ok with you.

**Comment by Perelyn-sama** [comment]
Please assign me to Events namespace

**Comment by jmcook1186** [comment]
Please assign me to validator namespace

**Comment by Perelyn-sama** [comment]
@jmcook1186 can I please work on validator namespace with you, we could split them

**Comment by ralexstokes** [comment]
@Perelyn-sama you can work on the `events` namespace if you want

here is some reference code from when I got this working in another context:

https://github.com/ralexstokes/ethereum_consensus_monitor/blob/main/src/beacon_api_client.rs#L126-L212

this code is a bit messy as I was hacking something together quickly but it may give you an idea of where to start

**Comment by ralexstokes** [comment]
I do think splitting up the `validator` namespace is a good idea :)


@jmcook1186 you want to take all of the HTTP `POST` methods?

and @Perelyn-sama you want to take the HTTP `GET` methods?

I think this will be easier to onboard @Perelyn-sama bc they are a bit simpler and @jmcook1186 can take the relatively more complicated `POST` methods

**Comment by ralexstokes** [comment]
if this works for you both @jmcook1186  and @Perelyn-sama , then @Perelyn-sama be aware of this PR which touches one method from your set https://github.com/ralexstokes/beacon-api-client/pull/51

**Comment by Perelyn-sama** [comment]
Sounds good to me, I'll handle the `GET` methods. 

@jmcook1186 can I have your discord handle? :) you could share it here - https://twitter.com/OkohEbina

**Comment by ralexstokes** [comment]
most of this has been done in existing merged PRs, ill close and move remaining work to other issues
